# You can find more wallpapers in ~/.config/ml4w/wallpapers/
# Run ~/.config/hypr/reload-hyprpaper.sh after changing your wallpaper

wallpaper {
  monitor = eDP-1
  path = /usr/share/backgrounds/Northern Forest.png
  fit_mode = cover
}

wallpaper {
  monitor = 
  path = /usr/share/backgrounds/Northern Forest.png
  fit_mode = cover
}

splash = false
